export interface WordClue {
  word: string;
  clue: string;
}

export const wordDatabase: Record<string, Record<string, Array<WordClue>>> = {
  animais: {
    facil: [
      { word: 'GATO', clue: 'Felino doméstico que faz miau' },
      { word: 'CACHORRO', clue: 'Melhor amigo do homem' },
      { word: 'PEIXE', clue: 'Animal que vive na água' },
      { word: 'PASSARO', clue: 'Animal que voa e tem penas' },
      { word: 'CAVALO', clue: 'Animal usado para montaria' },
      { word: 'VACA', clue: 'Animal que dá leite' },
      { word: 'PORCO', clue: 'Animal que vive na lama' },
      { word: 'GALINHA', clue: 'Ave que bota ovos' },
      { word: 'COELHO', clue: 'Animal que pula e come cenoura' },
      { word: 'RATO', clue: 'Pequeno roedor' },
      { word: 'OVELHA', clue: 'Animal que fornece lã' },
      { word: 'PATO', clue: 'Ave aquática que nada' },
      { word: 'GALO', clue: 'Macho da galinha' },
      { word: 'BURRO', clue: 'Animal de carga parecido com cavalo' },
      { word: 'CABRA', clue: 'Animal que come de tudo' },
      { word: 'ARANHA', clue: 'Animal de oito patas' },
      { word: 'ABELHA', clue: 'Inseto que faz mel' },
      { word: 'FORMIGA', clue: 'Inseto que trabalha em equipe' },
      { word: 'BORBOLETA', clue: 'Inseto colorido que voa' },
      { word: 'JOANINHA', clue: 'Inseto vermelho com pintinhas' }
    ],
    medio: [
      { word: 'ELEFANTE', clue: 'Maior mamífero terrestre' },
      { word: 'GIRAFA', clue: 'Animal mais alto do mundo' },
      { word: 'LEOPARDO', clue: 'Felino com manchas' },
      { word: 'RINOCERONTE', clue: 'Animal com chifre no nariz' },
      { word: 'CROCODILO', clue: 'Réptil que vive em rios' },
      { word: 'TUBARAO', clue: 'Predador dos oceanos' },
      { word: 'AGUIA', clue: 'Ave de rapina majestosa' },
      { word: 'FLAMINGO', clue: 'Ave rosa que vive em lagos' },
      { word: 'HIPOPOTAMO', clue: 'Grande mamífero aquático' },
      { word: 'CANGURU', clue: 'Animal que pula da Austrália' },
      { word: 'ZEBRA', clue: 'Cavalo com listras' },
      { word: 'LEAO', clue: 'Rei da selva' },
      { word: 'TIGRE', clue: 'Felino com listras' },
      { word: 'URSO', clue: 'Grande mamífero peludo' },
      { word: 'LOBO', clue: 'Ancestral selvagem do cão' },
      { word: 'RAPOSA', clue: 'Animal astuto de cauda peluda' },
      { word: 'VEADO', clue: 'Animal com chifres ramificados' },
      { word: 'JACARE', clue: 'Réptil brasileiro parente do crocodilo' },
      { word: 'PINGUIM', clue: 'Ave que não voa mas nada muito bem' },
      { word: 'CORUJA', clue: 'Ave noturna símbolo da sabedoria' }
    ],
    dificil: [
      { word: 'ORNITORRINCO', clue: 'Mamífero que bota ovos' },
      { word: 'AXOLOTE', clue: 'Anfibio que regenera membros' },
      { word: 'QUETZAL', clue: 'Ave sagrada dos maias' },
      { word: 'NUMBAT', clue: 'Mamífero insetívoro australiano' },
      { word: 'PANGOLIM', clue: 'Mamífero com escamas' },
      { word: 'OKAPI', clue: 'Parente da girafa' },
      { word: 'FOSSA', clue: 'Predador de Madagascar' },
      { word: 'QUOLL', clue: 'Marsupial carniceiro' },
      { word: 'BINTURONG', clue: 'Ursídeo asiático' },
      { word: 'CAPIVARA', clue: 'Maior roedor do mundo' },
      { word: 'TAPIR', clue: 'Mamífero com tromba curta' },
      { word: 'QUATI', clue: 'Parente do guaxinim' },
      { word: 'TAMANDUA', clue: 'Mamífero que come formigas' },
      { word: 'PREGUICA', clue: 'Animal muito lento das árvores' },
      { word: 'MORCEGO', clue: 'Único mamífero que voa' },
      { word: 'OURICO', clue: 'Animal coberto de espinhos' },
      { word: 'TATU', clue: 'Mamífero com carapaça' },
      { word: 'LONTRA', clue: 'Mamífero aquático brincalhão' },
      { word: 'CHINCHILA', clue: 'Roedor de pelo muito macio' },
      { word: 'SURICATA', clue: 'Animal que faz guarda em pé' }
    ]
  },
  ciencia: {
    facil: [
      { word: 'AGUA', clue: 'Líquido essencial à vida' },
      { word: 'SOL', clue: 'Estrela do nosso sistema' },
      { word: 'LUA', clue: 'Satélite natural da Terra' },
      { word: 'AR', clue: 'Mistura de gases que respiramos' },
      { word: 'FOGO', clue: 'Reação química com luz e calor' },
      { word: 'TERRA', clue: 'Nosso planeta' },
      { word: 'PLANTA', clue: 'Ser vivo que faz fotossíntese' },
      { word: 'ROCHA', clue: 'Material sólido da crosta terrestre' },
      { word: 'METAL', clue: 'Material condutor de eletricidade' },
      { word: 'GAS', clue: 'Estado da matéria sem forma fixa' },
      { word: 'OXIGENIO', clue: 'Gás que respiramos' },
      { word: 'CHUVA', clue: 'Água que cai do céu' },
      { word: 'VENTO', clue: 'Movimento do ar' },
      { word: 'GELO', clue: 'Água no estado sólido' },
      { word: 'VAPOR', clue: 'Água no estado gasoso' },
      { word: 'FERRO', clue: 'Metal que enferruja' },
      { word: 'OURO', clue: 'Metal precioso amarelo' },
      { word: 'CRISTAL', clue: 'Mineral transparente' },
      { word: 'ACIDO', clue: 'Substância que corrói' },
      { word: 'MAGNETISMO', clue: 'Força que atrai metais' }
    ],
    medio: [
      { word: 'MOLECULA', clue: 'Menor parte de uma substância' },
      { word: 'ELETRON', clue: 'Partícula com carga negativa' },
      { word: 'PROTON', clue: 'Partícula com carga positiva' },
      { word: 'NEUTRON', clue: 'Partícula sem carga elétrica' },
      { word: 'CROMOSSOMO', clue: 'Estrutura que contém genes' },
      { word: 'BACTERIA', clue: 'Microorganismo unicelular' },
      { word: 'VIRUS', clue: 'Agente infeccioso microscópico' },
      { word: 'CELULA', clue: 'Unidade básica da vida' },
      { word: 'ENZIMA', clue: 'Proteína que catalisa reações' },
      { word: 'GENOMA', clue: 'Conjunto completo de genes' },
      { word: 'CARBONO', clue: 'Elemento base da vida' },
      { word: 'HIDROGENIO', clue: 'Elemento mais simples' },
      { word: 'NITROGENIO', clue: 'Gás abundante na atmosfera' },
      { word: 'CALCIO', clue: 'Mineral dos ossos' },
      { word: 'CLORO', clue: 'Elemento do sal de cozinha' },
      { word: 'PLASMA', clue: 'Quarto estado da matéria' },
      { word: 'ANTIBIOTICO', clue: 'Remédio contra bactérias' },
      { word: 'PROTEINA', clue: 'Macromolécula construtora' },
      { word: 'CARBOIDRATO', clue: 'Fonte de energia rápida' },
      { word: 'LIPIDIO', clue: 'Gordura do organismo' }
    ],
    dificil: [
      { word: 'MITOCONDRIA', clue: 'Organela responsável pela respiração celular' },
      { word: 'RIBOSSOMO', clue: 'Organela que sintetiza proteínas' },
      { word: 'FOTOSSINTESE', clue: 'Processo de produção de glicose pelas plantas' },
      { word: 'MEIOSE', clue: 'Divisão celular que forma gametas' },
      { word: 'ESPERMATOGENESE', clue: 'Formação de espermatozoides' },
      { word: 'QUIMIOSSINTESE', clue: 'Síntese orgânica sem luz solar' },
      { word: 'HOMEOSTASE', clue: 'Manutenção do equilíbrio interno' },
      { word: 'ESTEQUIOMETRIA', clue: 'Cálculo de quantidades em reações químicas' },
      { word: 'HIBRIDIZACAO', clue: 'Mistura de orbitais atômicos' },
      { word: 'ELETROFORESE', clue: 'Separação de moléculas por carga elétrica' },
      { word: 'NUCLEOTIDEO', clue: 'Unidade básica do DNA' },
      { word: 'TRANSCRICAO', clue: 'Síntese de RNA a partir do DNA' },
      { word: 'TRADUCAO', clue: 'Síntese de proteínas' },
      { word: 'METAMORFOSE', clue: 'Transformação completa na forma' },
      { word: 'ECOSSISTEMA', clue: 'Sistema de seres vivos e ambiente' },
      { word: 'BIODIVERSIDADE', clue: 'Variedade de vida na Terra' },
      { word: 'TERMODINAMICA', clue: 'Estudo do calor e energia' },
      { word: 'ELETROMAGNETISMO', clue: 'Interação entre eletricidade e magnetismo' },
      { word: 'RADIOATIVIDADE', clue: 'Emissão de radiação nuclear' },
      { word: 'ENTROPIA', clue: 'Medida da desordem' }
    ]
  },
  geografia: {
    facil: [
      { word: 'BRASIL', clue: 'País onde vivemos' },
      { word: 'RIO', clue: 'Curso de água doce' },
      { word: 'MONTANHA', clue: 'Elevação natural do terreno' },
      { word: 'OCEANO', clue: 'Grande massa de água salgada' },
      { word: 'FLORESTA', clue: 'Área com muitas árvores' },
      { word: 'DESERTO', clue: 'Região muito seca' },
      { word: 'ILHA', clue: 'Terra cercada de água' },
      { word: 'LAGO', clue: 'Corpo de água doce cercado de terra' },
      { word: 'PRAIA', clue: 'Faixa de areia à beira-mar' },
      { word: 'CIDADE', clue: 'Área urbana com muitos habitantes' },
      { word: 'CAMPO', clue: 'Área rural com plantações' },
      { word: 'VALE', clue: 'Terreno baixo entre montanhas' },
      { word: 'PONTE', clue: 'Construção para atravessar rios' },
      { word: 'ESTRADA', clue: 'Caminho para veículos' },
      { word: 'PORTO', clue: 'Local onde param os navios' },
      { word: 'FAROL', clue: 'Torre que guia navegadores' },
      { word: 'MAPA', clue: 'Representação da Terra no papel' },
      { word: 'BUSSOLA', clue: 'Instrumento que aponta o norte' },
      { word: 'NORTE', clue: 'Ponto cardeal oposto ao sul' },
      { word: 'SUL', clue: 'Ponto cardeal onde fica a Antártida' }
    ],
    medio: [
      { word: 'AMAZONIA', clue: 'Maior floresta tropical do mundo' },
      { word: 'EQUADOR', clue: 'Linha imaginária que divide a Terra' },
      { word: 'TROPICO', clue: 'Linha de latitude próxima ao equador' },
      { word: 'MERIDIANO', clue: 'Linha imaginária de polo a polo' },
      { word: 'LATITUDE', clue: 'Distância angular do equador' },
      { word: 'LONGITUDE', clue: 'Distância angular do meridiano de Greenwich' },
      { word: 'PLATEAU', clue: 'Planalto elevado' },
      { word: 'PENINSULA', clue: 'Terra cercada de água em três lados' },
      { word: 'ARQUIPELAGO', clue: 'Conjunto de ilhas' },
      { word: 'TSUNAMI', clue: 'Onda gigante causada por terremoto' },
      { word: 'DELTA', clue: 'Foz de rio em formato triangular' },
      { word: 'FJORDE', clue: 'Vale glacial inundado pelo mar' },
      { word: 'CORDILHEIRA', clue: 'Cadeia de montanhas' },
      { word: 'PANTANAL', clue: 'Maior planície alagável do mundo' },
      { word: 'CAATINGA', clue: 'Vegetação do sertão nordestino' },
      { word: 'CERRADO', clue: 'Savana brasileira' },
      { word: 'PAMPAS', clue: 'Planície do sul do Brasil' },
      { word: 'MANGUE', clue: 'Vegetação dos litorais' },
      { word: 'TUNDRA', clue: 'Vegetação das regiões polares' },
      { word: 'TAIGA', clue: 'Floresta de coníferas' }
    ],
    dificil: [
      { word: 'GEODESIA', clue: 'Ciência que estuda a forma da Terra' },
      { word: 'TECTONISMO', clue: 'Movimento das placas terrestres' },
      { word: 'ISOSTASIA', clue: 'Equilíbrio da crosta terrestre' },
      { word: 'GEOMORFOLOGIA', clue: 'Estudo das formas do relevo' },
      { word: 'PEDOGENESE', clue: 'Formação dos solos' },
      { word: 'INTEMPERISMO', clue: 'Decomposição das rochas' },
      { word: 'PLUVIOSIDADE', clue: 'Quantidade de chuva em uma região' },
      { word: 'HIDROGRAFIA', clue: 'Estudo dos recursos hídricos' },
      { word: 'CARTOGRAFIA', clue: 'Arte e ciência de fazer mapas' },
      { word: 'TOPOGRAFIA', clue: 'Representação do relevo terrestre' },
      { word: 'BATIMETRIA', clue: 'Medição da profundidade oceânica' },
      { word: 'LITOSFERA', clue: 'Camada sólida externa da Terra' },
      { word: 'ASTENOSFERA', clue: 'Camada plástica do manto' },
      { word: 'VULCANISMO', clue: 'Atividade dos vulcões' },
      { word: 'OROGENIA', clue: 'Formação de montanhas' },
      { word: 'EPEIROGENIA', clue: 'Movimento vertical da crosta' },
      { word: 'SUBSIDENCIA', clue: 'Afundamento gradual do terreno' },
      { word: 'SOERGUIMENTO', clue: 'Elevação do terreno' },
      { word: 'ESCARPAMENTO', clue: 'Declive abrupto no terreno' },
      { word: 'PLANICIE', clue: 'Área plana de baixa altitude' }
    ]
  },
  historia: {
    facil: [
      { word: 'REI', clue: 'Governante de um reino' },
      { word: 'RAINHA', clue: 'Esposa do rei' },
      { word: 'CASTELO', clue: 'Fortaleza medieval' },
      { word: 'SOLDADO', clue: 'Pessoa que luta na guerra' },
      { word: 'ESPADA', clue: 'Arma branca de lâmina' },
      { word: 'ESCUDO', clue: 'Proteção do guerreiro' },
      { word: 'CAVALO', clue: 'Animal usado na guerra' },
      { word: 'BANDEIRA', clue: 'Símbolo de um país' },
      { word: 'COROA', clue: 'Adorno real na cabeça' },
      { word: 'TRONO', clue: 'Cadeira do rei' },
      { word: 'GUERRA', clue: 'Conflito entre países' },
      { word: 'PAZ', clue: 'Ausência de conflitos' },
      { word: 'BATALHA', clue: 'Combate entre exércitos' },
      { word: 'VITORIA', clue: 'Sucesso na guerra' },
      { word: 'HEROI', clue: 'Pessoa corajosa' },
      { word: 'LENDA', clue: 'História antiga transmitida oralmente' },
      { word: 'MITO', clue: 'História fantástica antiga' },
      { word: 'TESOURO', clue: 'Riquezas escondidas' },
      { word: 'PIRATA', clue: 'Ladrão dos mares' },
      { word: 'NAVEGADOR', clue: 'Explorador dos oceanos' }
    ],
    medio: [
      { word: 'PIRAMIDE', clue: 'Tumba dos faraós egípcios' },
      { word: 'FARAO', clue: 'Rei do antigo Egito' },
      { word: 'MUMIA', clue: 'Corpo preservado dos egípcios' },
      { word: 'GLADIADOR', clue: 'Lutador da arena romana' },
      { word: 'COLISEU', clue: 'Anfiteatro romano famoso' },
      { word: 'IMPERIO', clue: 'Grande território governado por imperador' },
      { word: 'REPUBLICA', clue: 'Governo eleito pelo povo' },
      { word: 'DEMOCRACIA', clue: 'Governo do povo' },
      { word: 'MONARQUIA', clue: 'Governo do rei' },
      { word: 'REVOLUCAO', clue: 'Mudança radical no governo' },
      { word: 'DESCOBRIMENTO', clue: 'Chegada dos portugueses ao Brasil' },
      { word: 'COLONIZACAO', clue: 'Ocupação de terras por outros povos' },
      { word: 'INDEPENDENCIA', clue: 'Libertação do domínio estrangeiro' },
      { word: 'ABOLICAO', clue: 'Fim da escravidão' },
      { word: 'PROCLAMACAO', clue: 'Anúncio oficial importante' },
      { word: 'INCONFIDENCIA', clue: 'Conspiração contra o governo' },
      { word: 'BANDEIRANTE', clue: 'Explorador do interior brasileiro' },
      { word: 'JESUITA', clue: 'Religioso que catequizava índios' },
      { word: 'QUILOMBO', clue: 'Comunidade de escravos fugidos' },
      { word: 'ENGENHO', clue: 'Fazenda de açúcar colonial' }
    ],
    dificil: [
      { word: 'RENASCIMENTO', clue: 'Movimento cultural dos séculos XV-XVI' },
      { word: 'ILUMINISMO', clue: 'Movimento filosófico do século XVIII' },
      { word: 'ABSOLUTISMO', clue: 'Governo com poder total do rei' },
      { word: 'MERCANTILISMO', clue: 'Sistema econômico colonial' },
      { word: 'FEUDALISMO', clue: 'Sistema social medieval' },
      { word: 'CRUZADAS', clue: 'Guerras religiosas medievais' },
      { word: 'INQUISICAO', clue: 'Tribunal religioso perseguidor' },
      { word: 'CONTRARREFORMA', clue: 'Reação católica ao protestantismo' },
      { word: 'REFORMA', clue: 'Movimento de Lutero contra a Igreja' },
      { word: 'CAPITALISMO', clue: 'Sistema econômico baseado no lucro' },
      { word: 'SOCIALISMO', clue: 'Sistema econômico coletivista' },
      { word: 'IMPERIALISMO', clue: 'Dominação de países por potências' },
      { word: 'NACIONALISMO', clue: 'Sentimento de amor à pátria' },
      { word: 'POSITIVISMO', clue: 'Filosofia de Augusto Comte' },
      { word: 'LIBERALISMO', clue: 'Ideologia da liberdade individual' },
      { word: 'JACOBINISMO', clue: 'Radicalismo da Revolução Francesa' },
      { word: 'GIRONDINOS', clue: 'Grupo moderado revolucionário francês' },
      { word: 'TERMIDOR', clue: 'Reação conservadora na França' },
      { word: 'BONAPARTISMO', clue: 'Regime político de Napoleão' },
      { word: 'RESTAURACAO', clue: 'Retorno da monarquia' }
    ]
  },
  matematica: {
    facil: [
      { word: 'SOMA', clue: 'Operação de adicionar números' },
      { word: 'MENOS', clue: 'Operação de subtração' },
      { word: 'VEZES', clue: 'Operação de multiplicação' },
      { word: 'DIVIDIR', clue: 'Operação de divisão' },
      { word: 'NUMERO', clue: 'Símbolo que representa quantidade' },
      { word: 'PAR', clue: 'Número divisível por dois' },
      { word: 'IMPAR', clue: 'Número não divisível por dois' },
      { word: 'ZERO', clue: 'Número que representa nada' },
      { word: 'UM', clue: 'Primeiro número natural' },
      { word: 'DEZ', clue: 'Base do sistema decimal' },
      { word: 'CEM', clue: 'Dez vezes dez' },
      { word: 'MIL', clue: 'Dez vezes cem' },
      { word: 'METADE', clue: 'Resultado de dividir por dois' },
      { word: 'DOBRO', clue: 'Resultado de multiplicar por dois' },
      { word: 'TRIPLO', clue: 'Resultado de multiplicar por três' },
      { word: 'CONTA', clue: 'Operação matemática' },
      { word: 'RESULTADO', clue: 'Resposta de uma operação' },
      { word: 'IGUAL', clue: 'Símbolo de igualdade' },
      { word: 'MAIOR', clue: 'Símbolo de comparação' },
      { word: 'MENOR', clue: 'Símbolo de comparação oposto' }
    ],
    medio: [
      { word: 'FRACAO', clue: 'Parte de um inteiro' },
      { word: 'DECIMAL', clue: 'Número com vírgula' },
      { word: 'PORCENTAGEM', clue: 'Parte de cem' },
      { word: 'QUADRADO', clue: 'Número multiplicado por si mesmo' },
      { word: 'CUBO', clue: 'Número elevado à terceira potência' },
      { word: 'RAIZ', clue: 'Operação inversa da potenciação' },
      { word: 'POTENCIA', clue: 'Número elevado a um expoente' },
      { word: 'EQUACAO', clue: 'Igualdade com incógnita' },
      { word: 'VARIAVEL', clue: 'Letra que representa número' },
      { word: 'CONSTANTE', clue: 'Número que não muda' },
      { word: 'ALGEBRA', clue: 'Matemática com letras' },
      { word: 'GEOMETRIA', clue: 'Estudo das formas' },
      { word: 'TRIANGULO', clue: 'Figura de três lados' },
      { word: 'QUADRADO', clue: 'Figura de quatro lados iguais' },
      { word: 'CIRCULO', clue: 'Figura redonda perfeita' },
      { word: 'PERIMETRO', clue: 'Contorno de uma figura' },
      { word: 'AREA', clue: 'Medida da superfície' },
      { word: 'VOLUME', clue: 'Medida do espaço ocupado' },
      { word: 'ANGULO', clue: 'Abertura entre duas retas' },
      { word: 'PARALELO', clue: 'Retas que nunca se encontram' }
    ],
    dificil: [
      { word: 'LOGARITMO', clue: 'Operação inversa da exponenciação' },
      { word: 'SENO', clue: 'Função trigonométrica básica' },
      { word: 'COSSENO', clue: 'Função trigonométrica complementar' },
      { word: 'TANGENTE', clue: 'Razão entre seno e cosseno' },
      { word: 'DERIVADA', clue: 'Taxa de variação instantânea' },
      { word: 'INTEGRAL', clue: 'Operação inversa da derivada' },
      { word: 'LIMITE', clue: 'Valor que uma função se aproxima' },
      { word: 'MATRIZ', clue: 'Tabela retangular de números' },
      { word: 'DETERMINANTE', clue: 'Número associado a uma matriz' },
      { word: 'VETOR', clue: 'Grandeza com módulo e direção' },
      { word: 'COMPLEXO', clue: 'Número com parte imaginária' },
      { word: 'INFINITO', clue: 'Quantidade sem fim' },
      { word: 'PROBABILIDADE', clue: 'Chance de um evento ocorrer' },
      { word: 'ESTATISTICA', clue: 'Ciência dos dados' },
      { word: 'VARIANCIA', clue: 'Medida de dispersão' },
      { word: 'DESVIO', clue: 'Diferença da média' },
      { word: 'CORRELACAO', clue: 'Relação entre variáveis' },
      { word: 'REGRESSAO', clue: 'Método de previsão estatística' },
      { word: 'BINOMIAL', clue: 'Expressão de dois termos' },
      { word: 'POLINOMIO', clue: 'Expressão de vários termos' }
    ]
  },
  esportes: {
    facil: [
      { word: 'FUTEBOL', clue: 'Esporte mais popular do Brasil' },
      { word: 'BOLA', clue: 'Objeto esférico usado nos jogos' },
      { word: 'GOL', clue: 'Ponto marcado no futebol' },
      { word: 'CAMPO', clue: 'Local onde se joga futebol' },
      { word: 'TIME', clue: 'Grupo de jogadores' },
      { word: 'JOGADOR', clue: 'Atleta que pratica esporte' },
      { word: 'CORRIDA', clue: 'Esporte de velocidade' },
      { word: 'NATACAO', clue: 'Esporte praticado na água' },
      { word: 'BASQUETE', clue: 'Esporte da cesta' },
      { word: 'VOLEI', clue: 'Esporte com rede no meio' },
      { word: 'TENIS', clue: 'Esporte com raquete' },
      { word: 'LUTA', clue: 'Combate entre dois atletas' },
      { word: 'BOXE', clue: 'Luta com luvas' },
      { word: 'JUDO', clue: 'Arte marcial japonesa' },
      { word: 'GOLFE', clue: 'Esporte com bastão e buraco' },
      { word: 'REMO', clue: 'Esporte aquático com barco' },
      { word: 'SURF', clue: 'Esporte das ondas' },
      { word: 'SKATE', clue: 'Esporte com prancha e rodas' },
      { word: 'BIKE', clue: 'Veículo de duas rodas para esporte' },
      { word: 'PISCINA', clue: 'Local para nadar' }
    ],
    medio: [
      { word: 'ATLETISMO', clue: 'Conjunto de modalidades olímpicas' },
      { word: 'GINASTICA', clue: 'Esporte de flexibilidade e força' },
      { word: 'HANDBALL', clue: 'Esporte parecido com futebol mas com as mãos' },
      { word: 'RUGBY', clue: 'Esporte violento parecido com futebol americano' },
      { word: 'BASEBALL', clue: 'Esporte americano com bastão' },
      { word: 'CRICKET', clue: 'Esporte inglês com wickets' },
      { word: 'BADMINTON', clue: 'Esporte com peteca' },
      { word: 'SQUASH', clue: 'Esporte em quadra fechada' },
      { word: 'POLO', clue: 'Esporte equestre com bastão' },
      { word: 'HIPISMO', clue: 'Esporte com cavalos' },
      { word: 'ESGRIMA', clue: 'Luta com espadas' },
      { word: 'ARCO', clue: 'Esporte de tiro com flecha' },
      { word: 'TIRO', clue: 'Esporte de precisão com armas' },
      { word: 'LEVANTAMENTO', clue: 'Esporte de força com pesos' },
      { word: 'MARATONA', clue: 'Corrida de longa distância' },
      { word: 'DECATLO', clue: 'Competição de dez modalidades' },
      { word: 'PENTATLO', clue: 'Competição de cinco modalidades' },
      { word: 'TRIATLO', clue: 'Competição de três modalidades' },
      { word: 'CICLISMO', clue: 'Esporte com bicicleta' },
      { word: 'MOTOCROSS', clue: 'Esporte com moto em trilha' }
    ],
    dificil: [
      { word: 'PARAOLIMPICO', clue: 'Esporte para pessoas com deficiência' },
      { word: 'PENTATHLON', clue: 'Competição militar com cinco provas' },
      { word: 'HEPTATHLON', clue: 'Competição feminina de sete provas' },
      { word: 'STEEPLECHASE', clue: 'Corrida com obstáculos e água' },
      { word: 'DECATHLON', clue: 'Competição masculina de dez provas' },
      { word: 'BOBSLED', clue: 'Esporte de inverno com trenó' },
      { word: 'SKELETON', clue: 'Descida de trenó de barriga' },
      { word: 'LUGE', clue: 'Descida de trenó sentado' },
      { word: 'CURLING', clue: 'Esporte de inverno com pedras' },
      { word: 'BIATHLON', clue: 'Esqui cross-country com tiro' },
      { word: 'CROSSFIT', clue: 'Treinamento funcional intenso' },
      { word: 'PARKOUR', clue: 'Arte de superação de obstáculos' },
      { word: 'CALISTENIA', clue: 'Exercícios com peso corporal' },
      { word: 'POWERLIFTING', clue: 'Levantamento de peso básico' },
      { word: 'STRONGMAN', clue: 'Competição de homem mais forte' },
      { word: 'FISICULTURISMO', clue: 'Esporte de desenvolvimento muscular' },
      { word: 'AQUATHLON', clue: 'Natação e corrida' },
      { word: 'DUATHLON', clue: 'Corrida e ciclismo' },
      { word: 'ORIENTACAO', clue: 'Esporte de navegação terrestre' },
      { word: 'GEOCACHING', clue: 'Caça ao tesouro com GPS' }
    ]
  }
};
